import { preCutoverInstructionBody } from "./preCutoverCommand.js";

export const PRIME_BLOB = preCutoverInstructionBody(
  [
    "# agentera priming guide",
    "",
    "## Routing: agentera vs native tools",
    "",
    "Use the top-level state-command namespace for routine questions about project state.",
    "Use native tools (read, grep, glob, edit, bash) for source code operations.",
    "",
    "Agentera queries return compact answers from structured state. Do NOT read",
    "raw YAML artifacts directly. The CLI is the seam between agent and state.",
    "",
    "For supported artifact mutations, use the typed state writer instead of native",
    "file edits. Discover the live fields and examples before constructing a write:",
    "  agentera state <artifact> explain --format json",
    "  agentera state <artifact> explain --verb <verb> --format json",
    "",
    "Supported state commands:",
    "  agentera prime                                # Composite orientation briefing",
    "  agentera prime --guidance                     # Print this guide",
    "  agentera state decisions [--topic TOPIC]      # Decision log",
    "  agentera state health [--dimension DIM]       # Latest health audit",
    "  agentera state todo [--severity LEVEL]        # TODO summary",
    "  agentera state plan                           # Plans, task evidence + provenance",
    "  agentera state progress [--limit N]           # Recent cycle summary",
    "  agentera state docs                           # Docs mappings + stale docs",
    "  agentera state objective                      # Active optimize objective",
    "  agentera state experiments                    # Active optimize experiments",
    "  agentera check lint --artifact PLAN.md --file plan.yaml  # Optional draft prose preview; the writer validates published bytes",
    "  agentera state query --list-artifacts         # Discover advanced schema names",
    "  agentera state query <artifact-name>          # Advanced custom artifact query",
    "",
    "Supported typed writes:",
    "  agentera state progress append ...            # Record verified cycle evidence",
    "  agentera state decisions explain --format json # Discover decision record operations",
    "  agentera state plan explain --format json      # Discover plan record operations",
    "  plan create ordinals are atomic-input symbols only; published plan/task identities are bare ten-letter IDs",
    "  agentera state health append --input PATH     # Record one complete audit",
    "  agentera state experiments publish --objective ID --input PATH  # Publish one validated experiment",
    "  Add --dry-run to preview any mutation without publishing it.",
    "",
    "When to use agentera:",
    '  - "What did we decide about X?"       → agentera state decisions --topic X',
    '  - "How\'s the codebase health?"        → agentera state health',
    '  - "What\'s the coupling grade?"        → agentera state health --dimension coupling_health',
    '  - "Any critical open issues?"         → agentera state todo --severity critical',
    "  - Recording supported artifact state   → agentera state <artifact> explain",
    "",
    "When to use native tools:",
    "  - Reading or editing source code      → native read/edit/grep",
    "  - Searching files                     → native glob/grep",
    "  - Running commands                    → native bash",
    "  - Browsing the web                    → native fetch",
    "",
    "## Recovery: stale or missing artifacts",
    "",
    "If `agentera <state>` returns empty:",
    "  1. The artifact may not exist yet (no data has been written to it).",
    "  2. Run without filters to see all available data.",
    "  3. If data is stale, the producing capability needs to run again.",
    "",
    "If entity state is corrupted:",
    "  1. Run `agentera check validate state --format json` for exact diagnostics.",
    "  2. Use the reported bare ID with `agentera state <artifact> get --id ID --format json`.",
    "  3. Follow the validator recovery; do not edit writer-owned entity files directly.",
    "",
    "If schemas are missing:",
    "  1. Run `agentera schema --format json`.",
    "  2. Make sure Agentera's app files exist at the reported `managedAppRoot` path.",
    "  3. Run `agentera doctor` for a plain-language repair preview.",
  ].join("\n") + "\n",
);
