export const PRIME_BLOB =
  [
    "# agentera priming guide",
    "",
    "## Routing: agentera vs native tools",
    "",
    "Use top-level `agentera <state>` commands for routine questions about project state.",
    "Use native tools (read, grep, glob, edit, bash) for source code operations.",
    "",
    "Agentera queries return compact answers from structured state. Do NOT read",
    "raw YAML artifacts directly. The CLI is the seam between agent and state.",
    "",
    "For supported artifact mutations, use the typed state writer instead of native",
    "file edits. Discover the live fields and examples before constructing a write:",
    "  agentera state <artifact> explain --format json",
    "  agentera state <artifact> explain --verb <verb> --format json",
    "",
    "Supported state commands:",
    "  agentera prime                                # Composite orientation briefing",
    "  agentera prime --guidance                     # Print this guide",
    "  agentera state decisions [--topic TOPIC]      # Decision log",
    "  agentera state health [--dimension DIM]       # Latest health audit",
    "  agentera state todo [--severity LEVEL]        # TODO summary",
    "  agentera state plan                           # Active plan, archive history + task status",
    "  agentera state progress [--limit N]           # Recent cycle summary",
    "  agentera state docs                           # Docs mappings + stale docs",
    "  agentera state objective                      # Active optimize objective",
    "  agentera state experiments                    # Active optimize experiments",
    "  agentera check lint --artifact PROGRESS.md --file .agentera/progress.yaml  # Pre-write artifact prose self-audit",
    "  agentera state query --list-artifacts         # Discover advanced schema names",
    "  agentera state query <artifact-name>          # Advanced custom artifact query",
    "",
    "Supported typed writes:",
    "  agentera state progress append ...            # Record verified cycle evidence",
    "  agentera state decisions append|update ...    # Record decisions or satisfaction",
    "  agentera state plan append|update|set-status|archive|create ...",
    "  agentera state health append --input PATH     # Record one complete audit",
    "  Add --dry-run to preview any mutation without publishing it.",
    "",
    "When to use agentera:",
    '  - "What did we decide about X?"       → agentera state decisions --topic X',
    '  - "How\'s the codebase health?"        → agentera state health',
    '  - "What\'s the coupling grade?"        → agentera state health --dimension coupling_health',
    '  - "Any critical open issues?"         → agentera state todo --severity critical',
    "  - Recording supported artifact state   → agentera state <artifact> explain",
    "",
    "When to use native tools:",
    "  - Reading or editing source code      → native read/edit/grep",
    "  - Searching files                     → native glob/grep",
    "  - Running commands                    → native bash",
    "  - Browsing the web                    → native fetch",
    "",
    "## Recovery: stale or missing artifacts",
    "",
    "If `agentera <state>` returns empty:",
    "  1. The artifact may not exist yet (no data has been written to it).",
    "  2. Run without filters to see all available data.",
    "  3. If data is stale, the producing capability needs to run again.",
    "",
    "If artifacts are corrupted:",
    "  1. Check the YAML file in .agentera/ directly.",
    "  2. Run `agentera schema --format json` and use `source.schemas_dir`.",
    "  3. Re-run the producing capability to regenerate the artifact.",
    "",
    "If schemas are missing:",
    "  1. Run `agentera schema --format json`.",
    "  2. Make sure Agentera's app files exist at the reported `managedAppRoot` path.",
    "  3. Run `agentera doctor` for a plain-language repair preview.",
  ].join("\n") + "\n";
