// Shared Research/Audit filing procedure, using the existing TODO writer.
export const findingsFiling = `## File selected findings

Filing is optional. Select actionable findings with the user; do not silently file all findings. Read existing TODOs through \`agentera state todo list\`, following every cursor needed for the comparison and exact \`get --id ID\` detail where needed. Deduplicate both within the selection and against tracked issues by meaning and evidence, not just title. Show excluded duplicates with their existing IDs. Do not reopen resolved work under filing approval; surface recurrence separately.

Read \`agentera state todo explain --verb create\` and its detail command. Prepare the exact selected full TODO records in the existing \`agentera.todoCreateBatch.v1\` envelope with stable request-local references. Map finding severity through \`agentera schema --protocol --section SEVERITY_MAPPING\`; show both finding and TODO severity. Preview with \`agentera state todo create --input REQUEST --dry-run\`. Display exactly the proposed titles, requirements, acceptance, severities, target versions, release-blocker flags and any readiness/dependencies, plus the count and destination. If nothing new remains, report already tracked and make no write.

Ask once: “File these selected findings as TODOs? This only saves the displayed set; it does not fix code, start another capability, or change vision.” Only an explicit Yes approves that unchanged set. No, silence or an unclear answer leaves TODO state unchanged. Do not require per-item prompts. A plan, analysis or execution approval is not filing approval.

After approval, apply the identical request using its preview \`effect_sha256\`: \`agentera state todo create --input REQUEST --effect-sha256 SHA256 --yes\`. Verify the returned local-reference IDs through exact TODO reads and report saved and remaining entries. Any changed entry, severity, additional finding or materially changed destination/effect needs a new preview and fresh approval; never refresh a rejected effect token under old approval. Approval covers filing only, never fixes, downstream execution or vision changes.

For interrupted or uncertain filing, retain the original request, effect token and returned IDs. Read saved entries and compare them with the approved records before reporting saved/remaining; unknown state is not success or permission to recreate. If a pending transaction blocks reads, report saved/remaining as unverified and follow the reader's exact-mutation recovery before repeating reads. Resume only the unchanged authorized batch with its original effect token, using the existing recovery/replay path. Do not create singles, re-preview a remaining subset or allocate a new batch to bypass recovery. Verify after retry; an exact completed replay must create no duplicates. If recovery rejects or approval/request evidence is missing, stop and report the gap before proposing a freshly checked set. Individual replacements and the writer's recovery are not a global atomic multi-file snapshot.

This is host guidance, not a consent security boundary. The CLI checks effect binding and replay; the host must obtain and preserve the user's approval before supplying \`--yes\`.
`;
