import fs from "node:fs";
import path from "node:path";

import { resolvePath } from "../core/paths.js";
import { resolveSourceRoot } from "../core/sourceRoot.js";
import { loadYamlMappingFile } from "../core/yaml.js";

/**
 * Release-metadata parity validator.
 *
 * Authority: TODO L21 — npm `@next` version-divergence gate.
 *
 * Background
 * ----------
 * The published npm `agentera` package ships its version through four
 * independent surfaces that must agree on the same release train:
 *
 *   1. `registry.json` `skills[0].version` — authoritative source of truth
 *      (per `references/adapters/package-registry.yaml` `version_authority`).
 *   2. `packages/cli/package.json` `version` — npm semver of the published CLI.
 *      May carry a pre-release suffix (e.g. `3.0.0-next.5`) on the `@next`
 *      development channel; the major.minor.patch prefix must match the
 *      authoritative version.
 *   3. `packages/cli/package.json` `agentera.suiteVersion` — mirror of the
 *      authoritative version; the docs and parity matrix consume this field
 *      when the registry is the only writable artifact.
 *   4. `packages/cli/package.json` `agentera.gitRef` — full 40-character git
 *      SHA the package was published from. A 7+ character short SHA or a
 *      branch name is rejected because the field is supposed to be
 *      reproducible from a single commit.
 *   5. `references/cli/update-channels.yaml` `version_resolution.latest_on_channel.offline_defaults`
 *      — what `agentera doctor` and `agentera upgrade` compare the running
 *      version against on each channel. The development default must match
 *      the authoritative version; the stable default is allowed to lag
 *      until explicit retirement per the channel compatibility boundary.
 *
 * Plus an advisory check on the local `packages/cli/bundle/.agentera-npx-bundle.json`
 * sentinel. The bundle directory is gitignored and regenerated by
 * `scripts/copy-bundle.mjs` at `prepack` time, so a stale local bundle is
 * not a release blocker — but the validator still flags it so maintainers
 * can `npm run bundle:data` after a version bump.
 *
 * The validator returns a list of error strings. The CLI surface in
 * `cli/commands/validate.ts` renders them as a non-zero exit so the
 * `check validate release-metadata` family can gate the doctor/upgrade
 * flow and the lefthook pre-commit hook.
 */

type Dict = Record<string, unknown>;

export interface ReleaseMetadataSnapshot {
  /** Authoritative version from `registry.json` `skills[0].version`. */
  authoritativeVersion: string | null;
  /** Authoritative version source path (relative to root). */
  authoritativeSource: string;
  /** `packages/cli/package.json` top-level `version`. */
  packageVersion: string | null;
  /** `packages/cli/package.json` `agentera.suiteVersion`. */
  packageSuiteVersion: string | null;
  /** `packages/cli/package.json` `agentera.gitRef`. */
  packageGitRef: string | null;
  /** `update-channels.yaml` `offline_defaults.development`. */
  developmentChannelDefault: string | null;
  /** `update-channels.yaml` `offline_defaults.stable`. */
  stableChannelDefault: string | null;
  /** Local `packages/cli/bundle/.agentera-npx-bundle.json` `suiteVersion` if present. */
  bundleSuiteVersion: string | null;
}

export const RELEASE_METADATA_AUTHORITY_FILES = [
  "registry.json",
  "packages/cli/package.json",
  "references/cli/update-channels.yaml",
] as const;

export const RELEASE_METADATA_ADVISORY_FILES = [
  "packages/cli/bundle/.agentera-npx-bundle.json",
] as const;

const SEMVER_CORE_RE = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
const SEMVER_STRICT_RE = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;
const PRE_RELEASE_RE = /-(.+)$/;
const GIT_REF_HEX_RE = /^[0-9a-f]{40}$/i;

function rootDefault(): string {
  return resolveSourceRoot();
}

function readJson(pathname: string): Dict | null {
  try {
    return JSON.parse(fs.readFileSync(pathname, "utf8")) as Dict;
  } catch {
    return null;
  }
}

function readRegistryVersion(root: string): { version: string | null; source: string } {
  const source = "registry.json";
  const data = readJson(path.join(root, source));
  if (data === null) {
    return { version: null, source };
  }
  const skills = data.skills;
  if (!Array.isArray(skills) || skills.length === 0) {
    return { version: null, source };
  }
  const first = skills[0];
  if (!first || typeof first !== "object") {
    return { version: null, source };
  }
  const version = (first as Dict).version;
  return { version: typeof version === "string" ? version : null, source };
}

function readPackageJson(root: string): Dict | null {
  const candidate = path.join(root, "packages/cli/package.json");
  if (!fs.existsSync(candidate)) {
    return null;
  }
  return readJson(candidate);
}

function readUpdateChannels(root: string): Dict | null {
  const candidate = path.join(root, "references/cli/update-channels.yaml");
  if (!fs.existsSync(candidate)) {
    return null;
  }
  try {
    return loadYamlMappingFile(candidate);
  } catch {
    return null;
  }
}

function readBundleSentinel(root: string): { version: string | null; source: string } {
  const source = "packages/cli/bundle/.agentera-npx-bundle.json";
  const candidate = path.join(root, source);
  if (!fs.existsSync(candidate)) {
    return { version: null, source };
  }
  const data = readJson(candidate);
  if (data === null) {
    return { version: null, source };
  }
  const version = data.suiteVersion;
  return { version: typeof version === "string" ? version : null, source };
}

/** Parse `X.Y.Z` core (ignore pre-release and build metadata). */
function parseSemverCore(version: string): { core: string; preRelease: string | null } | null {
  const match = SEMVER_CORE_RE.exec(version);
  if (!match) {
    return null;
  }
  const core = `${match[1]}.${match[2]}.${match[3]}`;
  const preMatch = PRE_RELEASE_RE.exec(version);
  return { core, preRelease: preMatch ? preMatch[1] : null };
}

function pickChannelDefaults(authority: Dict | null): {
  development: string | null;
  stable: string | null;
} {
  if (authority === null) {
    return { development: null, stable: null };
  }
  const versionResolution = authority.version_resolution as Dict | undefined;
  const latestOnChannel = versionResolution?.latest_on_channel as Dict | undefined;
  const defaults = (latestOnChannel?.offline_defaults ?? {}) as Dict;
  return {
    development: typeof defaults.development === "string" ? defaults.development : null,
    stable: typeof defaults.stable === "string" ? defaults.stable : null,
  };
}

export function readReleaseMetadata(root: string = rootDefault()): ReleaseMetadataSnapshot {
  const resolved = resolvePath(root);
  const registry = readRegistryVersion(resolved);
  const pkg = readPackageJson(resolved);
  const channels = readUpdateChannels(resolved);
  const bundle = readBundleSentinel(resolved);

  const topVersion = pkg && typeof pkg.version === "string" ? pkg.version : null;
  const agenteraBlock = pkg && typeof pkg.agentera === "object" && pkg.agentera !== null
    ? (pkg.agentera as Dict)
    : null;
  const suiteVersion = agenteraBlock && typeof agenteraBlock.suiteVersion === "string"
    ? agenteraBlock.suiteVersion
    : null;
  const gitRef = agenteraBlock && typeof agenteraBlock.gitRef === "string"
    ? agenteraBlock.gitRef
    : null;
  const { development, stable } = pickChannelDefaults(channels);

  return {
    authoritativeVersion: registry.version,
    authoritativeSource: registry.source,
    packageVersion: topVersion,
    packageSuiteVersion: suiteVersion,
    packageGitRef: gitRef,
    developmentChannelDefault: development,
    stableChannelDefault: stable,
    bundleSuiteVersion: bundle.version,
  };
}

/**
 * Validate release-metadata coherence. Returns an empty array when the
 * source-tree version surfaces agree on a single release train.
 */
export function validateReleaseMetadata(root: string = rootDefault()): string[] {
  const errors: string[] = [];
  const snap = readReleaseMetadata(root);
  const rootLabel = path.basename(resolvePath(root)) || "repo root";

  // 1. registry.json must publish a valid semver `skills[0].version`.
  if (snap.authoritativeVersion === null) {
    errors.push("registry.json: skills[0].version is required for release-metadata validation");
  } else {
    const parsed = parseSemverCore(snap.authoritativeVersion);
    if (parsed === null) {
      errors.push(
        `registry.json: skills[0].version ${JSON.stringify(snap.authoritativeVersion)} is not a valid semver`,
      );
    } else if (parsed.preRelease !== null) {
      // registry.json is the suite authority and stays on the released core;
      // pre-release suffixes belong only to packages/cli/package.json.
      errors.push(
        `registry.json: skills[0].version must be a released core version (no pre-release suffix); got ${JSON.stringify(snap.authoritativeVersion)}`,
      );
    }
  }

  // 2. packages/cli/package.json must exist and parse.
  if (snap.packageVersion === null && snap.packageSuiteVersion === null && snap.packageGitRef === null) {
    errors.push("packages/cli/package.json: missing or unreadable; cannot validate release-metadata");
  } else {
    // 2a. top-level `version` must be valid semver and share its core with registry.
    if (snap.packageVersion === null) {
      errors.push("packages/cli/package.json: top-level `version` is required");
    } else {
      const parsed = parseSemverCore(snap.packageVersion);
      if (parsed === null) {
        errors.push(
          `packages/cli/package.json: top-level version ${JSON.stringify(snap.packageVersion)} is not a valid semver`,
        );
      } else if (
        snap.authoritativeVersion !== null &&
        parseSemverCore(snap.authoritativeVersion)?.core !== parsed.core
      ) {
        errors.push(
          `release-metadata divergence: registry.json skills[0].version core is ${JSON.stringify(parseSemverCore(snap.authoritativeVersion)?.core)} ` +
            `but packages/cli/package.json top-level version core is ${JSON.stringify(parsed.core)}; ` +
            `the npm package version must share its major.minor.patch with the registry suite version`,
        );
      }
    }

    // 2b. `agentera.suiteVersion` must match registry exactly.
    if (snap.packageSuiteVersion === null) {
      errors.push("packages/cli/package.json: `agentera.suiteVersion` is required");
    } else if (
      snap.authoritativeVersion !== null &&
      snap.packageSuiteVersion !== snap.authoritativeVersion
    ) {
      errors.push(
        `release-metadata divergence: registry.json skills[0].version is ${JSON.stringify(snap.authoritativeVersion)} ` +
          `but packages/cli/package.json agentera.suiteVersion is ${JSON.stringify(snap.packageSuiteVersion)}; ` +
          `the agentera.suiteVersion mirror must equal the registry version exactly`,
      );
    } else if (!SEMVER_STRICT_RE.test(snap.packageSuiteVersion)) {
      errors.push(
        `packages/cli/package.json: agentera.suiteVersion ${JSON.stringify(snap.packageSuiteVersion)} is not a released core semver`,
      );
    }

    // 2c. `agentera.gitRef` must be a 40-character hex SHA.
    if (snap.packageGitRef === null || snap.packageGitRef === "") {
      errors.push("packages/cli/package.json: `agentera.gitRef` is required for release-metadata validation");
    } else if (!GIT_REF_HEX_RE.test(snap.packageGitRef)) {
      errors.push(
        `packages/cli/package.json: agentera.gitRef ${JSON.stringify(snap.packageGitRef)} must be a 40-character hex SHA; ` +
          `short SHAs and branch names are not reproducible release references`,
      );
    }
  }

  // 3. update-channels.yaml development default must equal the registry version.
  if (snap.developmentChannelDefault === null) {
    errors.push(
      "references/cli/update-channels.yaml: version_resolution.latest_on_channel.offline_defaults.development is required",
    );
  } else if (
    snap.authoritativeVersion !== null &&
    snap.developmentChannelDefault !== snap.authoritativeVersion
  ) {
    errors.push(
      `release-metadata divergence: registry.json skills[0].version is ${JSON.stringify(snap.authoritativeVersion)} ` +
        `but update-channels.yaml offline_defaults.development is ${JSON.stringify(snap.developmentChannelDefault)}; ` +
        `the development channel default must match the registry version exactly`,
    );
  }

  // 4. Stable channel default is informational on the @next branch; the
  // validator surfaces it so maintainers can confirm the stable line still
  // resolves to its declared 2.x version. A drift on the stable channel
  // alone is not an error here — that lane is owned by the `main` branch
  // compatibility boundary per `references/cli/update-channels.yaml`.
  void snap.stableChannelDefault;

  // 5. Advisory check on the local bundle sentinel.
  if (snap.bundleSuiteVersion !== null) {
    if (
      snap.authoritativeVersion !== null &&
      snap.bundleSuiteVersion !== snap.authoritativeVersion
    ) {
      errors.push(
        `release-metadata drift (advisory): packages/cli/bundle/.agentera-npx-bundle.json suiteVersion is ${JSON.stringify(snap.bundleSuiteVersion)} ` +
          `but registry.json skills[0].version is ${JSON.stringify(snap.authoritativeVersion)}; ` +
          `run \`npm run bundle:data\` (or \`pnpm -C packages/cli run bundle:data\`) at ${rootLabel} to refresh the local bundle copy before publishing`,
      );
    }
  }

  return errors;
}

export interface ReleaseMetadataMainOptions {
  root?: string;
  out?: (line: string) => void;
  err?: (line: string) => void;
}

export function releaseMetadataMain(opts: ReleaseMetadataMainOptions = {}): number {
  const root = resolvePath(opts.root ?? rootDefault());
  const out = opts.out ?? ((line: string) => process.stdout.write(line + "\n"));
  const err = opts.err ?? ((line: string) => process.stderr.write(line + "\n"));
  const errors = validateReleaseMetadata(root);
  if (errors.length > 0) {
    out("release-metadata validation failed:");
    for (const message of errors) out(`- ${message}`);
    return 1;
  }
  out("release-metadata ok");
  return 0;
}
